### ISSUE TITLE
check hours error - only happening for one user

### ISSUE THREAD

**Issue by mcmcford** [mcmcford/Charlies-Brain#9]
```
2021-12-28 10:47:24 - Beginning Process
2021-12-28 10:47:24 - checking user: ('225321172018003968', '76561198310339606', 1, 1, 1, 1, 87, None)
2021-12-28 10:47:24 - Sending API request
2021-12-28 10:47:25 - API Response: 200
2021-12-28 10:47:26 - checking user: ('131103291978285056', '76561198157513725', 1, 1, 1, 1, 646, None)
2021-12-28 10:47:26 - Sending API request
2021-12-28 10:47:26 - API Response: 200


2021-12-28 10:47:26 - Error:
Traceback (most recent call last):
  File "C:\Users\morga\Documents\python bots\Charlies-AI\apiloop.py", line 129, in get_steam_users
    await check_hours(game,game_from_db,thresholds)
  File "C:\Users\morga\Documents\python bots\Charlies-AI\apiloop.py", line 139, in check_hours
    if (int(game['playtime_forever']) != int(game_from_db[1])) and (int(game['playtime_forever']) != 0):
TypeError: 'NoneType' object is not subscriptable
2021-12-28 10:47:27 - checking user: ('320651607618355200', '76561198101599828', 1, 1, 1, 1, 307, None)
2021-12-28 10:47:27 - Sending API request
2021-12-28 10:47:27 - API Response: 200
2021-12-28 10:47:30 - checking user: ('188920806657622018', '76561198261286833', 1, 1, 1, 1, 219, None)
2021-12-28 10:47:30 - Sending API request
2021-12-28 10:47:30 - API Response: 200
2021-12-28 10:47:32 - checking user: ('664573756273983504', '76561199015218736', 1, 1, 1, 1, 43, None)
2021-12-28 10:47:32 - Sending API request
2021-12-28 10:47:33 - API Response: 200
2021-12-28 10:47:33 - checking user: ('279646933289795584', '76561198968734079', 1, 1, 1, 1, 59, None)
2021-12-28 10:47:33 - Sending API request
2021-12-28 10:47:34 - API Response: 200
2021-12-28 10:47:34 - checking user: ('331828582987071489', '76561198223803456', 1, 1, 1, 1, 290, None)
2021-12-28 10:47:34 - Sending API request
2021-12-28 10:47:34 - API Response: 200
2021-12-28 10:47:37 - checking user: ('133595114613374977', '76561198095996665', 1, 1, 1, 1, 145, None)
2021-12-28 10:47:37 - Sending API request
2021-12-28 10:47:38 - API Response: 200
2021-12-28 10:47:39 - checking user: ('219133269822799882', '76561198046483322', 1, 1, 1, 1, 170, None)
2021-12-28 10:47:39 - Sending API request
2021-12-28 10:47:40 - API Response: 200
2021-12-28 10:47:41 - checking user: ('471805778899238952', '76561198968840431', 1, 1, 1, 1, 72, None)
2021-12-28 10:47:41 - Sending API request
2021-12-28 10:47:41 - API Response: 200
```

**Comment by mcmcford** [comment]
Seems like the game wasn't added to the database for some reason, for now it will send a message into it's debug channel if it ever happens again at which point i'll likely add an exception handler for it
